### ISSUE TITLE
The canvas container's div css position should be relative instead of absolute.

### ISSUE THREAD

**Issue by mmzeeman** [stepan-mitkin/drakonwidget#1]
The canvas containers div has currently `position: absolute`. When the widget is drawn in a statically placed element, the widget will appear in the wrong place on the page. Usually relative to the body. 

When you change this to `position: relative` the embedded canvas and its containing divs will be placed relative to the element. This is probably more in line what people expect.

Example of statically placed widget container, which needs position relative.
<img width="1100" alt="Screen Shot 2022-10-28 at 16 21 17" src="https://user-images.githubusercontent.com/1024972/198641991-0842a8ea-e33c-41c2-b52a-75c1a5d60c7b.png">

**Comment by mmzeeman** [comment]
This is the way it is currently rendered. Outside its containing element.


<img width="1236" alt="Screen Shot 2022-10-28 at 16 29 57" src="https://user-images.githubusercontent.com/1024972/198646471-42e4f668-5b09-4351-8756-e36f87e64270.png">

**Comment by stepan-mitkin** [comment]
The position of the container is set to **relative**.
